### ISSUE TITLE
Issue while drop the existing database.

### ISSUE THREAD

**Issue by ganesh1997oli** [subsquid-labs/squid-ink-template#19]
I am following [ink contract indexing](https://docs.subsquid.io/tutorials/create-a-wasm-processing-squid/#define-the-data-schema) tutorial.
After running `sqd down`, `sqd process` stops and again runnign `sqd process` gives this issue as shown in image below.

<img width="1440" alt="Screenshot 2023-02-05 at 09 01 49" src="https://user-images.githubusercontent.com/42571338/216799676-e9e05b77-1bde-44e9-b5b0-8763c9de7bd9.png">

alos `sqd migrations:clean` gives issue after running.

"migrations clean" is not a sqd command.
Did you mean "migration clean"?
Run "sqd help" for a list of available commands.

**sqd version: `@subsquid/cli/2.1.0 darwin-x64 node-v18.13.0`**

**Comment by abernatskiy** [comment]
Please correct me if I'm wrong, but it seems like the issue is that the tutorial does not mention that `sqd process` **must be stopped** after the "Running the template" section and before doing any manipulations on the database. `sqd process` failing with an error when the database is not available is the expected behavior for Postgres-based squids.

Regarding the `migrations clean` issue: try fetching the fresh [`commands.json`](https://github.com/subsquid/squid-wasm-template/blob/master/commands.json) from the repository. This is the file that contains the local/intra-squid `sqd` scripts that show up when you run `sqd` in the squid folder. It has been updated in the template less than a day ago, so if you ran `sqd init` before that yours might be outdated.

**Comment by ganesh1997oli** [comment]
I don't know but I kind of get issue again while running `sqd generate`
ganesholi@Ganeshs-MacBook-Air my-ink-squid % sqd generate
GENERATE
    Error: spawn squid-gen-abi ENOENT
    Code: ENOENT
ganesholi@Ganeshs-MacBook-Air my-ink-squid %

**Comment by ganesh1997oli** [comment]
Even I tried to clone the `squid-wasm-template` and follow the quickstart section on github page, but while running `make build` got this error:

<img width="919" alt="Screenshot 2023-02-05 at 16 47 57" src="https://user-images.githubusercontent.com/42571338/216815292-f317c104-5845-4dbe-bdd4-df884dc06030.png">

**Comment by abernatskiy** [comment]
READMEs are outdated, apologies about that. For Ink! [the tutorial](https://docs.subsquid.io/tutorials/create-a-wasm-processing-squid/) is the best available source. It is pretty good, but it is also due for a review that will happen this coming week. Let me know if you have any issues with it and I'll fix them during the review.

`sqd generate` is currently only supported for squids based on the EVM processor. I just removed the corresponding scripts from `commands.json` in this repository to avoid confusion.

If you want an Ink! squid up and running pronto, you can use this integration testing script:
```bash
#!/bin/bash

sqd init my-squid --template ink &&
cd my-squid/ &&
npm i &&
sqd build &&
sqd up &&
sleep 2 &&
sqd migration:clean &&
sqd migration:generate &&
sqd process
```
This results in the squid ingestor process ("processor") running in the current terminal. If you then open another terminal in the squid folder and type `sqd serve`, you should get a working GraphQL API at [http://localhost:4350/graphql](http://localhost:4350/graphql).

**Comment by ganesh1997oli** [comment]
> READMEs are outdated, apologies about that. For Ink! [the tutorial](https://docs.subsquid.io/tutorials/create-a-wasm-processing-squid/) is the best available source. It is pretty good, but it is also due for a review that will happen this coming week. Let me know if you have any issues with it and I'll fix them during the review.
> 
> `sqd generate` is currently only supported for squids based on the EVM processor. I just removed the corresponding scripts from `commands.json` in this repository to avoid confusion.
> 
> If you want an Ink! squid up and running pronto, you can use this integration testing script:
> 
> ```shell
> #!/bin/bash
> 
> sqd init my-squid --template ink &&
> cd my-squid/ &&
> npm i &&
> sqd build &&
> sqd up &&
> sleep 2 &&
> sqd migration:clean &&
> sqd migration:generate &&
> sqd process
> ```
> 
> This results in the squid ingestor process ("processor") running in the current terminal. If you then open another terminal in the squid folder and type `sqd serve`, you should get a working GraphQL API at http://localhost:4350/graphql.

thank's for your response
